
WITH CUSTREVENUE AS (
SELECT C.CUSTOMERID, 
CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
COUNT(DISTINCT O.ORDERID) AS ORDERCOUNT,
SUM (OI.QUANTITY * OI.UNITPRICE) AS REVENUE
FROM EMART_OMS.L1_LANDING.CUSTOMERS C
JOIN EMART_OMS.L1_LANDING.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
JOIN EMART_OMS.L1_LANDING.ORDERITEMS OI
ON O.ORDERID = OI.ORDERID
GROUP BY C.CUSTOMERID, CUSTOMERNAME
ORDER BY REVENUE DESC
)


SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT, REVENUE FROM CUSTREVENUE
